name: Data Generator

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
      working-directory: data_generator
    - name: Run tests
      run: cargo test --verbose
      working-directory: data_generator
