name: Data Collection

on:
  push:
    paths:
    - 'data_collection/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: make build
      working-directory: data_collection
