name: Docker Image CI

on:
  push:
    paths:
      - data_collection

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the data collection docker image
      run: make build
      working-directory: data_collection
